
// Code generated by mockery v1.0.0. DO NOT EDIT.

package indicator

import mock "github.com/stretchr/testify/mock"

// MockIndicator is an autogenerated mock type for the Indicator type
type MockIndicator struct {
	mock.Mock
}

// Calculate provides a mock function with given fields: index
func (_m *MockIndicator) Calculate(index int) float64 {